
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CurrencyConvertor", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/CurrencyConvertor.asmx?WSDL")
public class CurrencyConvertor
    extends Service
{

    private final static URL CURRENCYCONVERTOR_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://www.webservicex.net/CurrencyConvertor.asmx?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CURRENCYCONVERTOR_WSDL_LOCATION = url;
    }

    public CurrencyConvertor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyConvertor() {
        super(CURRENCYCONVERTOR_WSDL_LOCATION, new QName("http://www.webserviceX.NET/", "CurrencyConvertor"));
    }

    /**
     * 
     * @return
     *     returns CurrencyConvertorSoap
     */
    @WebEndpoint(name = "CurrencyConvertorSoap")
    public CurrencyConvertorSoap getCurrencyConvertorSoap() {
        return (CurrencyConvertorSoap)super.getPort(new QName("http://www.webserviceX.NET/", "CurrencyConvertorSoap"), CurrencyConvertorSoap.class);
    }

}
